export default {
  schematizedEventTypes: {
    authButtonClick: "authButtonClick",
    authClientError: "authClientError",
    authPageLoad: "authPageload",
    passkeyRegistrationEvent: "passkeyRegistrationEvent",
  },
  context: {
    homepage: "homepage",
    accountSwitcherStatus: "accountSwitcherStatus",
    cachedUserChanged: "cachedUserChanged",
    auth401Modal: "signInRedirect",
    silentPasskeyUpgrade: "handleSilentPasskeyUpgradeWeb",
    silentPasskeyUpgradeWebLoginImmediate: "handleSilentPasskeyUpgradeWebLoginImmediate",
    silentPasskeyUpgradeWebLoginDelayed: "handleSilentPasskeyUpgradeWebLoginDelayed",
    silentPasskeyUpgradeWebSignupDelayed: "handleSilentPasskeyUpgradeWebSignupDelayed",
    passkeyRegistration: "passkeyRegistration",
  },
  passkeyRegistrationState: {
    navigationCredentialCreateFailure: "NavigationCredentialCreateFailure",
  },
  btn: {
    logout: "logout",
    switchAccount: "switchAccount",
    signIn: "signIn",
  },
  passkeyUpgradeState: {
    startRegistrationSuccess: "startRegistrationSuccess",
    startRegistrationError: "startRegistrationError",
    createCredentialError: "createCredentialError",
    invalidStateErrorHasExistingPasskey: "invalidStateErrorHasExistingPasskey",
    unknownError: "unknownError",
    finishRegistrationSuccess: "finishRegistrationSuccess",
    finishRegistrationError: "finishRegistrationError",
    httpStatusErrorParsing: "httpStatusErrorParsing",
    consumePasskeySessionFlagError: "consumePasskeySessionFlagError",
    silentUpgradeNotEligible: "silentUpgradeNotEligible",
    silentUpgradeCheckError: "silentUpgradeCheckError",
    expectedUserIdMissing: "expectedUserIdMissing",
    currentUserIdMissing: "currentUserIdMissing",
    userIdMismatch: "userIdMismatch",
    filteredByUnsupportedBrowser: "filteredByUnsupportedBrowser",
  },
} as const;
