export const PlayabilityStatus = {
  UnplayableOtherReason: "UnplayableOtherReason",
  Playable: "Playable",
  GuestProhibited: "GuestProhibited",
  GameUnapproved: "GameUnapproved",
  IncorrectConfiguration: "IncorrectConfiguration",
  UniverseRootPlaceIsPrivate: "UniverseRootPlaceIsPrivate",
  InsufficientPermissionFriendsOnly: "InsufficientPermissionFriendsOnly",
  InsufficientPermissionGroupOnly: "InsufficientPermissionGroupOnly",
  DeviceRestricted: "DeviceRestricted",
  UnderReview: "UnderReview",
  PurchaseRequired: "PurchaseRequired",
  AccountRestricted: "AccountRestricted",
  TemporarilyUnavailable: "TemporarilyUnavailable",
  ComplianceBlocked: "ComplianceBlocked",
  ContextualPlayabilityRegionalAvailability: "ContextualPlayabilityRegionalAvailability",
  ContextualPlayabilityRegionalCompliance: "ContextualPlayabilityRegionalCompliance",
  ContextualPlayabilityAgeRecommendationParentalControls:
    "ContextualPlayabilityAgeRecommendationParentalControls",
  ContextualPlayabilityAgeGated: "ContextualPlayabilityAgeGated",
  PlaceHasNoPublishedVersion: "PlaceHasNoPublishedVersion",
  ContextualPlayabilityUnverifiedSeventeenPlusUser:
    "ContextualPlayabilityUnverifiedSeventeenPlusUser",
  FiatPurchaseRequired: "FiatPurchaseRequired",
  ContextualPlayabilityUnrated: "ContextualPlayabilityUnrated",
  ContextualPlayabilityAgeGatedByDescriptor: "ContextualPlayabilityAgeGatedByDescriptor",
  ContextualPlayabilityExperienceBlockedParentalControls:
    "ContextualPlayabilityExperienceBlockedParentalControls",
  ContextualPlayabilityRequireParentApproval: "ContextualPlayabilityRequireParentApproval",
  ContextualPlayabilityCoreGated: "ContextualPlayabilityCoreGated",
  ContextualPlayabilityAgeCheckRequired: "ContextualPlayabilityAgeCheckRequired",
  FiatPurchaseDeviceRestricted: "FiatPurchaseDeviceRestricted",
} as const;
