enum LocalCreditBannerStage {
  NOT_STARTED = "NOT_STARTED",
  PRELAUNCH_BANNER_POSTED_1 = "PRELAUNCH_BANNER_POSTED_1",
  PRELAUNCH_BANNER_POSTED_2 = "PRELAUNCH_BANNER_POSTED_2",
  SERVICE_PAUSE = "SERVICE_PAUSE",
  ROLLOUT_STARTED = "ROLLOUT_STARTED",
}

export default LocalCreditBannerStage;
