// This should also be moved to Avatar Rules Api or something
export const assetTypeLabels: Record<number, string> = {
  2: "Label.ClassicTShirts",
  8: "Label.Hats",
  11: "Label.ClassicShirts",
  12: "Label.ClassicPants",
  17: "Label.Heads",
  18: "Label.Faces",
  19: "Label.Gear",
  27: "Label.Torsos",
  28: "Label.RightArms",
  29: "Label.LeftArms",
  30: "Label.LeftLegs",
  31: "Label.RightLegs",
  41: "Label.HairAccessories",
  42: "Label.FaceAccessories",
  43: "Label.NeckAccessories",
  44: "Label.ShoulderAccessories",
  45: "Label.FrontAccessories",
  46: "Label.BackAccessories",
  47: "Label.WaistAccessories",
  48: "Label.ClimbAnimations",
  50: "Label.FallAnimations",
  51: "Label.IdleAnimations",
  52: "Label.JumpAnimations",
  53: "Label.RunAnimations",
  54: "Label.SwimAnimations",
  55: "Label.WalkAnimations",
  61: "Heading.Emotes",
  64: "Label.TShirts",
  65: "Label.Shirts",
  66: "Label.Pants",
  67: "Label.Jackets",
  68: "Label.Sweaters",
  69: "Label.Shorts",
  70: "Label.LeftShoes",
  71: "Label.RightShoes",
  72: "Label.DressesAndSkirts",
};

export const avatarBodyPartIds = [27, 28, 29, 30, 31];
