const serverListConstants = {
  playerTruncationSize: 5, // will not truncate if set to -1
  slowGameFpsThreshold: 15,
  serverNameMaxLength: 50,
  numGameInstancesPerRow: 4,
  serverListTypes: {
    friend: {
      key: "friends",
      value: "Friend",
    },
    public: {
      key: "public",
      value: "Public",
    },
    Vip: {
      key: "private",
      value: "VIP",
    },
  },
  sortOrders: {
    descending: "Desc",
    ascending: "Asc",
  },
  // Values for the public server list "order by" dropdown. These map 1:1 to the
  // backend ServerListSortOption enum names. The occupancy options are equivalent
  // to the legacy Desc/Asc sortOrder; "recommended"/"bestLatency" are the newer
  // options.
  orderByOptions: {
    occupancyDesc: "OccupancyDesc",
    occupancyAsc: "OccupancyAsc",
    recommended: "Recommended",
    bestLatency: "BestLatency",
  },
  defaultOptions: {
    sortOrder: "Desc",
    excludeFullGames: false,
  },
  resources: {
    ascending: "Action.Ascending",
    atCapacityError: "Message.PrivateServersAtCapacity",
    buyNowText: "Action.BuyNow",
    cancelAction: "Action.Cancel",
    cancelPrivateServerText: "Action.CancelPrivateServer",
    cancelServerText: "Message.CancelServerConfirmation",
    cancelText: "Label.Cancel",
    cantJoinPrivacySettingText: "Label.NoOneCanJoinServerDueToPrivacySettings",
    configureServerText: "Action.ConfigureServer",
    confirmCancelText: "Action.ConfirmCancel",
    confirmEnableFuturePaymentsText: "Label.ConfirmEnableFuturePayments",
    createPrivateServerPriceText: "Label.CreatePrivateServerFor",
    createPrivateServerText: "Action.CreatePrivateServer",
    createPrivateServerTitle: "Action.CreatePrivateServer",
    createServerFooterDescription: "Description.RecurringSubscriptionRenewal",
    createServerFooterText: "Label.FooterText",
    descending: "Action.Descending",
    doNotCancelText: "Action.DoNotCancel",
    freeGameText: "Label.Free",
    friendInServerLabel: "Label.FriendInServer",
    friendsServersTitle: "Heading.ServersMyFriendsAreIn",
    gameNameText: "Label.GameName",
    hideFullServers: "Label.ExcludeFullServers",
    inactiveServerText: "Label.Inactive",
    insufficientFunds: "Label.InsufficientFunds",
    joinServerText: "Label.ServerListJoin",
    loadMoreButtonText: "Action.LoadMore",
    loadServersError: "Message.LoadServersFailure",
    manyFriendsInServerLabel: "Label.ManyFriendsInServer",
    maxFreePrivateServersText: "Description.MaxFreePrivateServers",
    noServersFoundText: "Label.NoServersFound",
    numberOfPlayers: "Label.NumberOfPlayers",
    perMonthText: "Label.PerMonth",
    pricePerMonthText: "Label.PricePerMonth",
    playerCountText: "Label.CurrentPlayerCount",
    privacySettingsText: "Label.PrivacySettings",
    privateServerHeader: "Heading.PrivateServers",
    privateServerLabel: "Label.PrivateServer",
    privateServerPlayWithOthers: "Label.PlayWithOthers",
    privateServerPrice: "Label.Price",
    privateServerRefreshText: "Action.Refresh",
    privateServersNotSupported: "Label.VipServersNotSupported",
    privateServerTooltip: "Label.PrivateServersAbout",
    publicServersTitle: "Heading.OtherServers",
    purchaseError: "Message.InternalErrorPurchaseError",
    renewalCanceledText: "Label.RenewalCanceled",
    renewPrivateServerTitle: "Label.RenewPrivateServer",
    renewServerListText: "Label.Renew",
    renewsMonthlyText: "Label.RenewsMonthlyCancelAnytime",
    renewSubscriptionError: "Message.RenewSubscriptionError",
    renewSubscriptionSuccess: "Message.RenewSubscriptionSuccess",
    serverCancellationSuccess: "Message.ServerCancellationSuccess",
    serverNameText: "Label.ServerName",
    serverIdText: "Label.ServerId",
    // Feature.ServerList — public server list "sort by" dropdown
    sortByLabel: "Label.SortBy",
    recommendedForYou: "Label.RecommendedForYou",
    bestLatency: "Label.BestLatency",
    occupancyDescending: "Label.OccupancyDescending",
    occupancyAscending: "Label.OccupancyAscending",
    serversFailedToLoadText: "Message.LoadServersFailure", // Feature.ServerList
    shutdownServerError: "Message.ShutdownServerError",
    shutdownServerSuccess: "Message.ShutdownServerSuccess",
    shutdownServerText: "Label.ShutDownServer",
    slowGameWarning: "Label.SlowGame",
    startRenewingPrivateServerPrice: "Label.StartRenewingPrivateServerPrice",
    closeText: "Action.Close",
    subscribeText: "Action.Subscribe",
    // Feature.PrivateServers — private server revamp
    yourPrivateServersTitle: "Heading.YourPrivateServers",
    privateServersSubtitle: "Description.PrivateServersSubtitle",
    placeNamePrivateServer: "Label.PlaceNamePrivateServer",
    requiresSubscriptionText: "Label.RequiresSubscription",
    freeWithBlackbirdText: "Action.FreeWithBlackbird",
    limitedToServersText: "Label.LimitedToServers",
    createOneForFreeText: "Action.CreateOneForFree",
    createAPrivateServerText: "Label.CreateAPrivateServer",
    includedWithBlackbirdText: "Label.IncludedWithBlackbird",
    createText: "Action.Create",
    createPrivateServerSheetTitle: "Title.CreatePrivateServer",
    subscribeToServerSheetTitle: "Title.SubscribeToServer",
    subscriptionLegalText: "Description.PrivateServerSheetSubscriptionLegal",
    freeServerLimitReachedText: "Label.FreePrivateServerLimitReached",
    unlimitedIncludedWithBlackbirdText: "Label.UnlimitedIncludedWithBlackbird",
    getUnlimitedWithBlackbirdText: "Label.GetUnlimitedFreeServersWithBlackbird",
    blackbirdLabel: "Label.Blackbird",
    getBlackbirdTitle: "Title.GetBlackbird",
    blackbirdPriceTag: "Label.BlackbirdPriceTag",
    blackbirdPSDiscount: "Label.BlackbirdPSDiscount",
    blackbirdDiscountBase: "Description.Benefit.DiscountBase",
    blackbirdRobuxTransfers: "Description.Benefit.RobuxTransfers",
    freeTrialPrice: "Description.FreeTrialPrice",
    blackbirdVTDiscountSecond: "Label.BlackbirdVTDiscountSecond",
    subscriptionLegal: "Description.SubscriptionLegal",
    ownersServerText: "Label.OwnersServer",
    privateServerCreatedText: "Label.PrivateServerCreated",
    joinText: "Action.Join",
    // Feature.ServerList — player hosted events
    createPlayerHostedEventText: "Label.CreatePlayerHostedEvent",
    playerHostedEventSubtitle: "Label.PlayerHostedEventSubtitle",
    createPlayerHostedEventCardTitle: "Label.CreateAPlayerHostedEvent",
    createPlayerHostedEventCardSubtitle: "Label.HostAScheduledEventForYourFriends",
    // Feature.ServerList — private server revamp
    joinYourFriendsTitle: "Heading.JoinYourFriends",
    joinFriendsSubtitle: "Description.JoinFriendsSubtitle",
    otherServersSubtitle: "Description.OtherServersSubtitle",
    loadingText: "Label.Loading",
    transactionFailedHeading: "Heading.TransactionFailed",
    twoFriendsInServerLabel: "Label.TwoFriendsInServer",
    // Purchasing.PurchaseDialog
    headingInsufficientFunds: "Heading.InsufficientFunds",
    economicRestrictionsErrorHeading: "Heading.EconomicRestrictionsError",
  },
  economicRestrictionLabel: {
    // IAPExperience.PurchaseError
    FraudPaymentAuthorizationAttempt: "Label.Sublabel.FraudPaymentAbuse",
    FraudVirtualEconomyAbuse: "Label.Sublabel.FraudVirtualEconomyAbuse",
    FraudAbuseOfAffiliateSystem: "Label.Sublabel.FraudAbuseOfTheAffiliateSystem",
    FraudAttemptedUnauthorizedPaymentMethodUse:
      "Label.Sublabel.FraudAttemptedUnauthorizedPaymentMethodUse",
    FraudRepeatedRefundRequests: "Label.Sublabel.FraudRepeatedRefundRequests",
    FraudSuspiciousRefundRequests: "Label.Sublabel.FraudSuspiciousRefundRequests",
    FraudUnauthorizedPurchase: "Label.Sublabel.FraudUnauthorizedPurchase",
    FraudUseOfUnauthorizedOffPlatformTransactions:
      "Label.Sublabel.FraudUseOfUnauthorizedOffPlatformTransactions",
    FraudUseOfUnauthorizedPaymentMethod: "Label.Sublabel.FraudUseOfUnauthorizedPaymentMethod",
    FraudSuspiciousAccountPatterns: "Label.Sublabel.FraudSuspiciousAccountPatterns",
    // Feature.NotApproved
    FraudChargeback: "Label.AbuseType.Chargeback",
  },
} as const;

export default serverListConstants;
