export const COOKIE_NAME = "RBXPaymentsFlowContext";
export const COOKIE_TIMESPAN = 600;

export const enum EVENT_NAME {
  USER_PURCHASE_FLOW = "UserPurchaseFlow",
  USER_PURCHASE_STATUS = "UserPurchaseStatus",
}

/**
 * IMPORTANT: When adding values in this enum, update the corresponding
 * data pipeline context_to_flow_and_client_mapping in powerhouse-pipelines repo:
 * k8s/economy/payfrud/purchase_funnels/purchase_funnel_constants.py for flow attribution.
 */
export enum TRIGGERING_CONTEXT {
  WEB_ROBUX_PURCHASE = "WebRobuxPurchase",
  MOBILE_WEB_ROBUX_PURCHASE = "MobileWebRobuxPurchase",
  MOBILE_WEB_PREMIUM_PURCHASE = "MobileWebPremiumPurchase",
  WEB_PREMIUM_PURCHASE = "WebPremiumPurchase",
  WEB_CATALOG_ROBUX_UPSELL = "WebCatalogRobuxUpsell",
  WEB_CATALOG_PREMIUM_UPSELL = "WebCatalogPremiumUpsell",
  WEB_CATALOG_COLLECTIVE_ITEM_ROBUX_UPSELL = "WebCatalogCollectiveItemRobuxUpsell",
  WEB_CATALOG_BUNDLE_ITEM_ROBUX_UPSELL = "WebCatalogBundleItemRobuxUpsell",
  WEB_PAID_GAME_ROBUX_UPSELL = "WebPaidGameRobuxUpsell",
  WEB_GAME_PASS_ROBUX_UPSELL = "WebGamePassRobuxUpsell",
  WEB_DEVELOPER_PRODUCT_ROBUX_UPSELL = "WebDeveloperProductRobuxUpsell",
  WEB_PRIVATE_SERVER_ROBUX_UPSELL = "WebPrivateServerRobuxUpsell",
  WEB_CATALOG_CART_ROBUX_UPSELL = "WebCatalogCartRobuxUpsell",
  WEBVIEW_ROBUX_PURCHASE = "WebViewRobuxPurchase",
  WEBVIEW_PREMIUM_PURCHASE = "WebViewPremiumPurchase",
  WEB_ROBUX_GIFT_PURCHASE = "WebRobuxGiftPurchase",
  WEB_ROBUX_GIFT_POST_CHECKOUT = "WebRobuxGiftPostCheckout",
  WEB_GIFT_CARD_PURCHASE = "WebGiftCardPurchase",
  WEB_REDEEM_PAGE = "WebRedeemPage",
  WEB_PAYMENT_METHODS_SETTING = "WebPaymentMethodsSetting",
  WEB_ROBLOX_PLUS_PURCHASE = "WebRobloxPlusPurchase",
  MOBILE_WEB_ROBLOX_PLUS_PURCHASE = "MobileWebRobloxPlusPurchase",
  WEBVIEW_ROBLOX_PLUS_PURCHASE = "WebViewRobloxPlusPurchase",
  WEB_CATALOG_SINGLE_ITEM_PLUS_UPSELL = "WebCatalogSingleItemPlusUpsell",
  WEB_CATALOG_RESALE_ITEM_PLUS_UPSELL = "WebCatalogResaleItemPlusUpsell",
  WEB_CATALOG_BUNDLE_ITEM_PLUS_UPSELL = "WebCatalogBundleItemPlusUpsell",
  WEB_DEVELOPER_SUBSCRIPTION_PLUS_UPSELL = "WebDeveloperSubscriptionPlusUpsell",
  WEB_GAME_PASS_PLUS_UPSELL = "WebGamePassPlusUpsell",
  WEB_DEVELOPER_PRODUCT_PLUS_UPSELL = "WebDeveloperProductPlusUpsell",
  WEB_PRIVATE_SERVER_PLUS_UPSELL = "WebPrivateServerPlusUpsell",
  WEB_APP_THEME_PLUS_UPSELL = "WebAppThemePlusUpsell",
}

export enum VIEW_NAME {
  ROBUX_UPSELL = "RobuxUpsell",
  ROBUX_UPSELL_EXCEED_LARGEST_PACKAGE = "RobuxUpsellExceedLargestPackage",
  PURCHASE_WARNING = "PurchaseWarning",
  LEAVE_ROBLOX_WARNING = "LeaveRobloxWarning",
  PREMIUM_DISCLOSURES = "PremiumDisclosures",
  PRODUCT_PURCHASE = "ProductPurchase",
  PRODUCT_PURCHASE_IMPRESSION = "ProductPurchaseImpression",
  PRODUCT_PURCHASE_LOADING = "ProductPurchaseLoading",
  PRODUCT_PURCHASE_QUICK_PAY = "ProductPurchaseQuickPay",
  QUICK_PAY_3DS = "QuickPay3DS",
  PREMIUM_PURCHASE = "PremiumPurchase",
  MEMBERSHIP = "Membership",
  MEMBERSHIP_ANGULAR = "MembershipAngular",
  PREMIUM_UPSELL = "PremiumUpsell",
  PAYMENT_METHOD = "PaymentMethod",
  MOBILE_PAYMENT_METHOD = "MobilePaymentMethod",
  MOBILE_PAYMENT_METHOD_SAMSUNG_PAY = "MobilePaymentMethodSamsungPay",
  MOBILE_PAYMENT_METHOD_REDEEM_CREDIT = "MobilePaymentMethodRedeemCredit",
  NAVIGATION_MENU = "NavigationMenu",
  PREPARE_PAYMENT_ERROR_OCCURRED = "PreparePaymentErrorOccured",
  XSOLLA = "Xsolla",
  XSOLLA_OTHER = "Xsolla Other",
  XSOLLA_SAVED_PAYMENT_METHOD = "Xsolla SavedCard",
  PAYPAL_POST_PROCESS = "Paypal Post Process",
  BRAINTREE_POST_PROCESS = "Braintree Post Process",
  BRAINTREE_PAYPAL_SAVED_PAYMENT = "Braintree PayPal Checkout With Saved Profile",
  ROBLOX_CREDIT = "Roblox Credit",
  ROBLOX_CREDIT_CHECKOUT = "Roblox Credit Checkout",
  ROBLOX_CREDIT_CHECKOUT_WITH_TAX = "Roblox Credit Checkout With Tax",
  ROBLOX_CREDIT_CHECKOUT_WITHOUT_TAX = "Roblox Credit Checkout Without Tax",
  ROBLOX_CREDIT_CAPTCHA = "Roblox Credit Captcha",
  LOADING = "Loading",
  CHECKOUT_SUCCESS = "Checkout Success",
  MOBILE_WEB_CHECKOUT_SUCCESS = "MobileWebCheckoutSuccess",
  SUCCESS = "Success",
  ERROR = "Error",
  NAVIGATION_ROBUX_TEXT = "NavigationRobuxText",
  NAVIGATION_DROPDOWN_MENU = "NavigationDropdownMenu",
  LEFT_NAVIGATION_BAR = "LeftNavigationBar",
  TRANSACTION_PAGE = "TransactionPage",
  CATALOG_LIST_PAGE = "CatalogListPage",
  ROBLOX_CREDIT_SETTING_BILLING_PAGE = "RobloxCreditBillingPage",
  REDEEM_ROBLOX_CARD_PAGE = "RedeemRobloxCardPage",
  PURCHASE_VPC_MODAL = "PurchaseVpcModal",
  OPTIMIZED_PURCHASE_VPC_MODAL = "OptimizedPurchaseVpcModal",
  ROBUX_GIFT_LANDING_PAGE = "RobuxGiftLandingPage",
  ROBUX_GIFT_BUNDLE_MESSAGE_PAGE = "RobuxGiftBundleMessagePage",
  ROBUX_GIFT_PRODUCT_SELECTION = "RobuxGiftProductSelection",
  ROBUX_GIFT_MESSAGE_SELECTION = "RobuxGiftMessageSelection",
  ROBUX_GIFT_PHONE_SUBMISSION = "RobuxGiftPhoneSubmission",
  ROBUX_GIFT_PHONE_AUTHENTICATION = "RobuxGiftPhoneAuthentication",
  ROBUX_GIFT_POST_CHECKOUT_SUCCESS = "RobuxGiftPostCheckoutSuccess",
  ROBUX_GIFT_POST_CHECKOUT_FAILURE = "RobuxGiftPostCheckoutFailure",
  ROBUX_GIFT_REQUEST_BANNER = "WebRobuxGiftRequestBanner",
  GIFT_CARD = "GiftCard",
  SHOP_GIFT_CARDS = "ShopGiftCards",
  ECONOMIC_RESTRICTION_ERROR = "EconomicRestrictionError",
  CREDIT_PACKAGE_PURCHASE_MODAL_WITH_TAX = "CreditPackagePurchaseModalWithTax",
  CREDIT_PACKAGE_PURCHASE_MODAL_WITHOUT_TAX = "CreditPackagePurchaseModalWithoutTax",
  CREDIT_CONVERSION_MODAL_WITH_TAX = "CreditConversionModalWithTax",
  CREDIT_CONVERSION_MODAL_WITHOUT_TAX = "CreditConversionModalWithoutTax",
  CREDIT_BALANCE_BIILLING_ADDRESS_FORM = "CreditBalanceBillingAddressForm",
  ROBUX_REDIRECT_BANNER = "RobuxRedirectBanner",
  NUVEI_REDIRECTED_TO_EXTERNAL_PAYMENT_PAGE = "NuveiRedirectedToExternalPaymentPage",
  NUVEI_SIMPLY_CONNECT_LOADED = "NuveiSimplyConnectLoaded",
  NUVEI_TRANSACTION_APPROVED = "NuveiTransactionApproved",
  NUVEI_TRANSACTION_DECLINED = "NuveiTransactionDeclined",
  NUVEI_TRANSACTION_PENDING = "NuveiTransactionPending",
  NUVEI_SESSION_TIMED_OUT = "NuveiSessionTimedOut",
  NUVEI = "Nuvei",
  ROBUX_GIFT = "RobuxGift",
  ROBUX_GIFT_MODAL = "RobuxGiftModal",
  POST_PURCHASE = "PostPurchase",
  FIRST_TIME_PURCHASE_CONSENT_MODAL = "FirstTimePurchaseConsentModal",
  ROBLOX_PLUS_LANDING = "RobloxPlusLanding",
  ROBLOX_PLUS_UPSELL_BANNER = "RobloxPlusUpsellBanner",
  ROBLOX_PLUS_BUY_ROBUX = "RobloxPlusBuyRobux",
  ROBUX_SEND_TRANSFERS = "RobuxSendTransfers",
  ROBUX_PENDING_TRANSFERS = "RobuxPendingTransfers",
  REDEEM_CREDIT_FOOTER = "RedeemCreditFooter",
  REDEEM_CREDIT_GET_PLUS_MODAL = "RedeemCreditGetPlusModal",
}

export enum PURCHASE_EVENT_TYPE {
  VIEW_SHOWN = "ViewShown",
  USER_INPUT = "UserInput",
}

export enum VIEW_MESSAGE {
  SUBMIT_ORDER = "Submit Order",
  REDEEM = "Redeem",
  BUY_ROBUX = "Buy Robux",
  BUY_ROBUX_AND_ITEM = "Buy Robux and Item",
  BUY_GIFT_CARD = "Buy Gift Card",
  CONTINUE_TO_CASHSTAR = "Continue to Cashstar",
  CONTINUE_TO_VNG = "Continue to Vng",
  EXTERNAL_LINK_MODAL = "External Link Modal",
  CANCEL = "Cancel",
  CLOSE = "Close",
  CONTINUE = "Continue",
  BACK = "Back",
  CARD_NUMBER_FORM = "Card Number Form",
  PAY_NOW = "Pay Now",
  PROCEED_TO_CHECKOUT = "Proceed to Checkout",
  SEND_RECEIPT_TO_EMAIL = "Send receipt to email",
  OPEN_EXTERNAL_LINK = "External Link",
  PAYMENT_METHOD_LIST = "Other payment method list",
  GIFT_CARD = "Gift Card",
  OK = "OK",
  PREMIUM = "Premium",
  GET_PREMIUM = "Get Premium",
  GO_TO_ROBUX_STORE = "Go To Robux Store",
  U13_PAYMENT_MODAL = "U13PaymentModal",
  U13_PARENTAL_CONSENT_WARNING = "U13ParentalConsentWarning",
  PAYMENT_MODAL_13_TO_17 = "PaymentModal13To17",
  U13_MONTHLY_THRESHOLD_1_MODAL = "U13MonthlyThreshold1Modal",
  U13_MONTHLY_THRESHOLD_2_MODAL = "U13MonthlyThreshold2Modal",
  REQUIRE_EMAIL_VERIFICATION = "RequireEmailVerification",
  PURCHASE = "PURCHASE",
  REQUIRE_TWO_STEP_VERIFICATION = "RequireTwoStepVerification",
  ROBUX_ICON = "Robux Icon",
  PAGE_REFRESHED = "PageRefreshed",
  BACK_FORWARD_DETECTED = "Back/Forward Triggered",
  PAGE_LOADED_FROM_BACK_FORWARD_CACHE = "Back/Forward Triggered & Loaded From Cache",
  GO_TO_ROBUX_PURCHASE_PAGE = "Go to Robux Purchase Page",
  BILLING_EMAIL_NOT_PREFILLED = "Billing Email Not Prefilled",
  CREDIT_CONVERSION = "Credit Conversion",
  GO_TO_SETTINGS = "Go to Settings",
  PREPARE_PAYMENT_REQUEST_FETCH_FAILED = "PreparePaymentRequestFetchFailed",
  PREPARE_PAYMENT_REQUEST_FLOOD_CHECKED = "PreparePaymentRequestFloodChecked",
  PREPARE_PAYMENT_REQUEST_REDIRECTED = "PreparePaymentRequestRedirected",
  PAYMENT_METHOD_DROPDOWN = "Payment Method Dropdown",
  USE_DIFFERENT_PAYMENT_METHOD = "Use Different Payment Method",
  SAMSUNG_PAY_SELECTED = "Samsung Pay Selected",
  REDEEM_CREDIT_SELECTED = "Redeem Credit Selected",
  GIFT_NOW = "Gift now",
  CHECKOUT = "Checkout",
  VERIFY = "Verify",
  REQUEST_ROBUX = "Request Robux",
  BUY_NOW = "Buy Now",
  ADD_TO_CART = "Add to Cart",
  GIFT_CARD_AMOUNT_BUTTON = "GiftCardAmountButton",
  GIFT_CARD_TYPE_BUTTON = "GiftCardTypeButton",
  GIFT_CARD_RECIPIENT_TYPE_BUTTON = "GiftCardRecipientTypeButton",
  JOIN = "Join",
  BUY_REDIRECT = "Buy (redirect)",
  RETURN_TO_APP = "Return to app",
  SHOW_MORE = "Show more",
  SHOW_LESS = "Show less",
  TOGGLE_ON = "Toggle (on)",
  TOGGLE_OFF = "Toggle (off)",
  BUY = "Buy",
  PURCHASE_SUCCESS = "Purchase Success",
  CONFIRM = "Confirm",
  ROBLOX_PLUS_FREE_TRIAL = "RobloxPlusFreeTrial",
  ROBLOX_PLUS_SUBSCRIBE = "RobloxPlusSubscribe",
  ROBLOX_PLUS_BUNDLE_SHEET_OPENED = "RobloxPlusBundleSheetOpened",
  ROBLOX_PLUS_BUNDLE_TIER_SELECTED = "RobloxPlusBundleTierSelected",
  ROBLOX_PLUS_LEARN_MORE = "RobloxPlusLearnMore",
  TRANSFER_SEND_BUTTON = "TransferSendButton",
  TRANSFER_SEND_SHEET = "TransferSendSheet",
  TRANSFER_SEND_USER_SELECTED = "TransferSendUserSelected",
  TRANSFER_PENDING_BUTTON = "TransferPendingButton",
  TRANSFER_PENDING_SHEET = "TransferPendingSheet",
  TRANSFER_PENDING_ACCEPT_CLICK = "TransferPendingAcceptClick",
  GET_PLUS_CLICKED = "GetPlusClicked",
  GET_ROBUX_CLICKED = "GetRobuxClicked",
  TIER_SELECTED = "TierSelected",
  SUBSCRIBE_CLICKED = "SubscribeClicked",
}

export enum PURCHASE_STATUS {
  ABANDONED = "Abandoned",
  FAILED_PREPARE_PAYMENT_REQUEST = "FailedPreparePaymentRequest",
  PASSED_PREPARE_PAYMENT_REQUEST = "PassedPreparePaymentRequest",
  PASSED_PREPARE_PAYMENT_REQUEST_WITH_TAX = "PassedPreparePaymentRequestWithTax",
  FAILED_UPDATE_ADDRESS_FOR_CHECKOUT_SESSION = "FailedUpdateAddressForCheckoutSession",
  PASSED_UPDATE_ADDRESS_FOR_CHECKOUT_SESSION = "PassedUpdateAddressForCheckoutSession",
  FAILED_GET_APPROXIMATE_USER_LOCATION = "FailedGetApproximateUserLocation",
  PASSED_GET_APPROXIMATE_USER_LOCATION = "PassedGetApproximateUserLocation",
  FAILED_PROCESS_PAYMENT = "FailedProcessPayment",
  PASSED_PROCESS_PAYMENT = "PassedProcessPayment",
  FAILED_GET_NEXT_PURCHASABLE_METADATA = "FailedGetNextPurchasableMetadata",
  PASSED_GET_NEXT_PURCHASABLE_METADATA = "PassedGetNextPurchasableMetadata",
  REDIRECTED_TO_PREMIUM_PAGE = "RedirectedToPremiumPage",
  EXISTING_FLOW_OVERWRITTEN_BY = "ExistingFlowOverwrittenBy",
  PAYMENT_FLOW_STARTED = "PaymentFlowStarted",
  BROWSER_PAGE_CHANGED = "BrowserPageChanged",
  CAPTCHA = "Captcha",
  SUCCESS = "Success",
  ERROR = "Error",
  CONTINUE = "Continue",
  CANCEL = "Cancel",
  PAYMENT_FLOW_ENDED = "PaymentFlowEnded",
}

export const enum ASSET_TYPE {
  GAME_PASS = "Game Pass",
  PRIVATE_SERVER = "Private Server",
  BUNDLE = "Bundle",
  PACKAGE = "Package",
  PLACE = "Place",
  DEVELOPER_PRODUCT = "Product",
  SUBSCRIPTION = "Subscription",
}

const COUNTER_PREFIX = "UserPaymentFlow";
export const COUNTER_EVENTS = {
  WRONG_USAGE_OF_METHOD: `${COUNTER_PREFIX}WrongUsageOfMethod`,
  PRE_LOADED_FROM_COOKIE: `${COUNTER_PREFIX}PreLoadedFromCookie`,
  EXISTING_FLOW_OVERWRITTEN_TRIGGERED: `${COUNTER_PREFIX}ExistingFlowOverwrittenTriggered`,
  NEW_FLOW_INITIATED_PREFIX: `${COUNTER_PREFIX}NewFlowInitiatedFor`,
  WRONG_DATA_IN_COOKIE: `${COUNTER_PREFIX}WrongDataInCookie`,
  STATUS_EVENT_TRIGGERED_WITHOUT_CTX: `${COUNTER_PREFIX}StatusEventTriggeredWithoutCtx`,
  MID_PURCHASE_STEP_TRIGGERED_WITHOUT_VALID_REFERRER: `${COUNTER_PREFIX}MidPurchaseStepTriggeredWithoutValidReferrer`,
  MID_PURCHASE_STEP_TRIGGERED_WITH_REFRESH: `${COUNTER_PREFIX}MidPurchaseStepTriggeredWithRefresh`,
  MID_PURCHASE_STEP_TRIGGERED_WITHOUT_VALID_CTX: `${COUNTER_PREFIX}MidPurchaseStepTriggeredWithoutCtx`,
  SEND_EVENT_WITHOUT_UUID_OR_CTX: `${COUNTER_PREFIX}SendEventWithoutUuidOrCtx`,
  FLOW_ABANDONED_DETECTED: `${COUNTER_PREFIX}FlowAbandoned`,
  PAGE_REFRESHED: `${COUNTER_PREFIX}PageRefreshed`,
  BACK_FORWARD_DETECTED: `${COUNTER_PREFIX}BackForwardDetected`,
  PAGE_LOADED_FROM_BACK_FORWARD_CACHE: `${COUNTER_PREFIX}BackForwardDetectedLoadedFromCache`,
  LOAD_PRE_EXISTING_CTX_ERROR: `${COUNTER_PREFIX}LoadPreExistingCtxError`,
  SEND_STATUS_EVENT_ERROR: `${COUNTER_PREFIX}SendStatusEventError`,
  SEND_USER_EVENT_ERROR: `${COUNTER_PREFIX}SendUserEventError`,
  START_FLOW_ERROR: `${COUNTER_PREFIX}StartFlowError`,
  EVENTS_REGISTER_ERROR: `${COUNTER_PREFIX}EventsRegisterError`,
  PERFORMANCE_NAVIGATION_TYPE_ERROR: `${COUNTER_PREFIX}PerformanceNavigationTypeError`,
  FLOW_ENDED: `${COUNTER_PREFIX}FlowEnded`,
};

export enum CUSTOM_EVENT {
  FLOW_CONTINUE = "payment-user-journey:continue",
  FLOW_REFERRER_VALID = "payment-user-journey:referrer-valid",
}

export enum PAGE_LOAD_TYPE {
  NAVIGATE = "navigate",
  RELOAD = "reload",
  BACK_FORWARD = "back_forward",
}
