import { addExternal } from "@rbx/externals";
import {
  AvatarCardItem,
  AvatarCardList,
  ItemCard,
  itemCardUtils,
  Banner,
  Button,
  IconButton,
  DatePicker,
  NativeDropdown,
  Dropdown,
  FileUpload,
  FilterSelect,
  Form,
  FormControl,
  FormGroup,
  Image,
  Link,
  Loading,
  Modal,
  SimpleModal,
  createModal,
  Pagination,
  ProgressBar,
  Popover,
  ScrollBar,
  Section,
  SystemFeedback,
  createSystemFeedback,
  useSystemFeedback,
  SystemFeedbackProvider,
  SimpleTab,
  SimpleTabs,
  Tabs,
  Toast,
  Toggle,
  Tooltip,
  TextFormField,
} from "@rbx/core-ui";

import "./main.css";

addExternal("ReactStyleGuide", {
  AvatarCardItem,
  AvatarCardList,
  Banner,
  Button,
  DatePicker,
  Dropdown,
  FileUpload,
  FilterSelect,
  Form,
  FormControl,
  FormGroup,
  IconButton,
  Image,
  ItemCard,
  Link,
  Loading,
  Modal,
  NativeDropdown,
  Pagination,
  Popover,
  ProgressBar,
  ScrollBar,
  Section,
  SimpleModal,
  SimpleTab,
  SimpleTabs,
  SystemFeedback,
  Tabs,
  TextFormField,
  Toast,
  Toggle,
  Tooltip,
  createSystemFeedback,
  useSystemFeedback,
  SystemFeedbackProvider,
  createModal,
  ItemCardUtils: itemCardUtils,
});
