import { TranslationConfig } from "react-utilities";

export const FEATURE_NAME = "SecurityTab" as const;
export const LOG_PREFIX = "Security Tab:" as const;

export const STATE_PROPERTIES_ELEMENT_ID = "state-properties";
export const SESSION_MANAGEMENT_ELEMENT_ID = "session-management";

// The URL of the Forgot Password support page.
export const FORGOT_PASSWORD_SUPPORT_URL =
  "https://en.help.roblox.com/hc/articles/203313070-I-Forgot-My-Password" as const;

// Maximum number of security keys user can register.
export const MAX_KEY_COUNT = 5;

// Timeout value for hybridResponseService getNativeResponse call.
export const NATIVE_RESPONSE_TIMEOUT_MILISECONDS = 300000;

/**
 * Constants for event stream events.
 */
export const EVENT_CONSTANTS = {
  settingsContext: "settings",
  button: {
    twoStepVerificationEnabled: "turn2SVon",
    twoStepVerificationDisabled: "turn2SVoff",
    verificationWarningSecurityPageTriggered: "verificationWarningSecurityPageTriggered",
    codeInputModalTriggered: "codeInputModalTriggered",
    verifySecurityPage: "verifySecurityPage",
  },
} as const;

/**
 * Constants for EPP schematized events (lands in accountauth_* tables).
 */
export const EPP_EVENT_CONSTANTS = {
  schematizedEventTypes: {
    authButtonClick: "authButtonClick",
    authModalShown: "authModalShown",
  },
  context: {
    eppCard: "eppCard",
    eppDetails: "eppDetails",
    eppEmailModal: "eppEmailModal",
    eppPhoneModal: "eppPhoneModal",
    eppUnenrollWarning: "eppUnenrollWarning",
  },
  btn: {
    open: "open",
    back: "back",
    addPasskey: "addPasskey",
    managePasskey: "managePasskey",
    addEmail: "addEmail",
    editEmail: "editEmail",
    addPhone: "addPhone",
    editPhone: "editPhone",
    enroll: "enroll",
    unenroll: "unenroll",
    confirmUnenroll: "confirmUnenroll",
    cancelUnenroll: "cancelUnenroll",
    createBackupCodes: "createBackupCodes",
    createAgainBackupCodes: "createAgainBackupCodes",
  },
  state: {
    enrolled: "enrolled",
    unenrolled: "unenrolled",
  },
} as const;

/**
 * Translations required by this web app (remember to also edit
 * `bundle.config.js` if changing this configuration).
 */
export const TRANSLATION_CONFIG: TranslationConfig = {
  common: [],
  feature: "Feature.AccountSettings",
};

/**
 * Language resource keys for Account Settings.
 */
export const ACCOUNT_SETTINGS_LANGUAGE_RESOURCES = [
  "Action.Add",
  "Action.AddSecurityKey",
  "Action.AddPasskey",
  "Action.DeleteSecurityKey",
  "Action.Dialog.AddEmail",
  "Action.Dialog.AddPhone",
  "Action.Dialog.AuthenticatorHelpMessage",
  "Action.Dialog.AuthenticatorSetupViewManualEntryKey",
  "Action.Dialog.AuthenticatorSetupViewQRCode",
  "Action.Dialog.Cancel",
  "Action.Dialog.Close",
  "Action.Dialog.Continue",
  "Action.Dialog.EditEmail",
  "Action.Dialog.EditPhonePrimary",
  "Action.Dialog.EnterPhoneNumber",
  "Action.Dialog.EnterSentCode",
  "Action.Dialog.ForgotYourPassword",
  "Action.Dialog.PendingEmailVerification",
  "Action.Dialog.ResendCode",
  "Action.Dialog.ResendCodeWithTimer",
  "Action.Dialog.SixDigitCode",
  "Action.Dialog.Success",
  "Action.Dialog.Verify",
  "Action.Dialog.VerifyCode",
  "Action.Clear",
  "Action.Create",
  "Action.Delete",
  "Action.Done",
  "Action.Edit",
  "Action.CreateAgain",
  "Action.EnableEnhancedProtectionProgram",
  "Action.Generate",
  "Action.ManagePasskey",
  "Action.PasskeyAlreadyExists",
  "Action.PasskeyCreated",
  "Action.PasskeyRemoved",
  "Action.SocialDisconnect",
  "Action.TurnOff",
  "Action.TurnOffEnhancedProtectionProgram",
  "Body.Enrolled",
  "Body.Unenrolled",
  "Description.ClearRecoveryCodesWarning",
  "Description.Dialog.AuthenticatorSetupManualEntryKey",
  "Description.Dialog.AuthenticatorSetupQRCode",
  "Description.Dialog.ChangeEmailWarning",
  "Description.Dialog.EnterYourPassword",
  "Description.Dialog.MissingEmailTwoStepVerification",
  "Description.Dialog.MissingEmailTwoStepVerificationU13",
  "Description.Dialog.MissingPhoneTwoStepVerification",
  "Description.Dialog.RecoveryCodesGenerated",
  "Description.Dialog.ShortCodeLegalDisclaimer",
  "Description.Dialog.SmsInstructions",
  "Description.Dialog.UnverifiedEmailOrPhoneTwoStepVerification",
  "Description.SecurityKey.AuthenticatorOff",
  "Description.SecurityKey.Delete",
  "Description.SecurityKey.DeleteWarning",
  "Description.SecurityKey.DeleteSuccess",
  "Description.SecurityKey.Deletion",
  "Description.SecurityKey.NameKey",
  "Description.SecurityKey.Register2SV",
  "Description.SecurityKey.SetupError",
  "Description.SecurityKey.Warning",
  "Description.SecurityKey.WebOnly",
  "Description.SecurityWarning",
  "Description.SecurityWarningShort",
  "Description.SmsTwoStepVerificationSecondaryEnabled",
  "Description.TurnOffEnhancedProtectionProgram",
  "Description.TurnOnLowerSecurity2SVMethod",
  "Description.TwoStepverificationSecondaryEnabled",
  "Description.TwoStepVerificationNone",
  "Description.NewNoneDescription2SV",
  "Description.EnhancedProtectionProgram",
  "Description.CardEnhancedProtectionProgramDetails",
  "Heading.ClearRecoveryCodes",
  "Heading.DeleteSecurityKey",
  "Heading.DeleteSecurityKeySuccess",
  "Heading.Dialog.AreYouSure",
  "Heading.Dialog.AuthenticatorSetup",
  "Heading.Dialog.DefaultError",
  "Heading.Dialog.OneOptionAtATime",
  "Heading.Dialog.PasswordVerification",
  "Heading.Dialog.VerifiedEmailOrPhoneRequired",
  "Heading.Dialog.VerifiedPhoneRequired",
  "Heading.GenerateNewRecoveryCodes",
  "Heading.ManageYourKeys",
  "Heading.NameSecurityKey",
  "Heading.PlayStation",
  "Heading.RecoveryCodesGenerated",
  "Heading.RegisterSecurityKey",
  "Heading.Tab.Security",
  "Heading.SecurityKey",
  "Heading.SecurityKey2",
  "Heading.SecurityKey.PlatformNotSupported",
  "Heading.SecurityKeyRegistered",
  "Heading.SomethingWentWrong",
  "Heading.TurnOnAuthenticator",
  "Heading.TwoStepVerification",
  "Heading.Xbox",
  "Heading.EnhancedProtectionProgram",
  "Label.AuthenticatorDisabledHelpText",
  "Label.AuthenticatorHelpText",
  "Label.AuthenticatorTwoStepVerificationCodes",
  "Label.Cancel",
  "Label.Dialog.AuthenticatorSetupCodeInputPlaceholder",
  "Label.Dialog.Confirm",
  "Label.Dialog.EmailRequired",
  "Label.Dialog.GenerateNewRecoveryCodesClearNotice",
  "Label.Dialog.RecoveryCodesSavedConfirmation",
  "Label.Dialog.YourPassword",
  "Label.DisableAuthenticator.Acknowledge",
  "Label.DropDown.None",
  "Label.EmailTwoStepVerificationCodes",
  "Label.EnterEmail",
  "Label.GenerateNewRecoveryCodes",
  "Label.GenerateRecoveryCodes",
  "Label.AddBothOfThese",
  "Label.BackupCodes",
  "Label.BackupCodesDescription",
  "Label.DoNotShare",
  "Label.ChooseOneOfThese",
  "Label.HaveVerifiedEmail",
  "Label.HaveVerifiedPhone",
  "Label.HavePasskeys",
  "Label.Loading",
  "Label.Manage",
  "Label.PasskeyAdded",
  "Label.AddPasskeyEnsureAccess",
  "Label.PasskeysAddedEnsureAccess",
  "Label.PlayStationConnected",
  "Label.RecoveryCodesHelpText",
  "Label.SecurityKey",
  "Label.SecurityKeyAuthenticator",
  "Label.SecurityKey.BiometricKey",
  "Label.SecurityKey.Name",
  "Label.SecurityKey.PhysicalKey",
  "Label.SecurityKey.RegisteredKey",
  "Label.SecurityKey.RegisteredKeysAtCapacity",
  "Label.SecurityKey.TurnOnAuthenticator",
  "Label.SmsTwoStepPrerequisite",
  "Label.SmsTwoStepVerificationCodes",
  "Label.TwoStepPrerequisite",
  "Label.TwoStepVerificationDescription",
  "Label.TwoStepVerificationEmailWarningNew",
  "Label.TwoStepVerificationPopUpEmailWarning",
  "Label.TwoStepVerificationSingleMethodDescription",
  "Label.UnusedRecoveryCodes",
  "Label.Verify",
  "Label.XboxConnected",
  "Message.Error.AlreadyEnabled",
  "Message.Error.EmailAlreadyRegisteredToAccount",
  "Message.Error.Email.IncorrectPassword",
  "Message.Error.Email.PinLocked",
  "Message.Error.ExceededRegisteredKeysLimit",
  "Message.Error.InvalidCredentialNickname",
  "Message.Error.InvalidEmail",
  "Message.Error.NoVerifiedEmail",
  "Message.Error.ReauthenticationRequired",
  "Message.Error.TooManyRequests",
  "Message.ItemTradeTwoStepVerificationMessage",
  "Message.ManualKeyCopied",
  "Message.ResaleTwoStepVerificationMessage",
  "Message.RobuxSpendTwoStepVerificationMessage",
  "MessageUnknownError",
  "Response.Dialog.AuthenticatorSessionExpired",
  "Response.Dialog.DefaultErrorMessage",
  "Response.Dialog.DisconnectPlayStationError",
  "Response.Dialog.DisconnectXBoxError",
  "Response.Dialog.EnableTwoStepVerificationSingleMethodWarning",
  "Response.Dialog.InvalidCodeError",
  "Response.Dialog.InvalidPhoneNumber",
  "Response.Dialog.TwoStepDisableAdditionalWarningAuthenticator",
  "Response.Dialog.TwoStepDisableAdditionalWarningAuthenticatorGeneric",
  "Response.Dialog.TwoStepDisableWarning",
  "Response.Dialog.TwoStepDisableWarningAuthenticator",
  "Response.Dialog.TwoStepDisableWarningEmail",
  "Response.Dialog.Warning",
  "Response.Dialog.DeleteSecurityKeyWarning",
  "Response.FeatureDisabled",
  "Response.GeneralError",
  "Response.PasskeyAlreadyCreated",
  "Response.PasskeyCreatedSuccessfully",
  "Response.PasskeyRemovedSuccessfully",
  "Response.SuccessfulVerificationV2",
  "Response.VerificationError",
] as const;
