import "./src/main.css";
import Roblox from "@rbx/legacy-webapp-types/Roblox";
import {
  addAssetToAvatar,
  removeAssetFromAvatar,
  removeAssetTypesFromAvatar,
  removeLayeredClothingFromAvatar,
  getAssetTypeById,
  getAssetTypeByName,
  getAssetTypeByType,
  getAssetTypeNameById,
  getLayeredClothingAssetOrder,
  getAdvancedAccessoryLimit,
  isAccessoryType,
  isAnimation,
  isEmote,
  isLayeredClothing,
  isDynamicHead,
  isDynamicHeadInAssetList,
  isNonAvatarAssetType,
  isProfileBackground,
  buildMetaForAsset,
  insertAssetMetaIntoAssetList,
  buildMetaForAssets,
  maxNumberOfLayeredClothingItems,
  maxNumberOfAdvancedAccessoryItems,
  isBodyPart,
  layeredClothingRefinementOrderOffset,
  getCategories,
} from "@rbx/avatar-common/src/accoutrementRules/services/accoutrementRulesService";

Roblox.AvatarAccoutrementService = {
  addAssetToAvatar,
  removeAssetFromAvatar,
  removeAssetTypesFromAvatar,
  removeLayeredClothingFromAvatar,
  getAssetTypeById,
  getAssetTypeByName,
  getAssetTypeByType,
  getAssetTypeNameById,
  getLayeredClothingAssetOrder,
  getAdvancedAccessoryLimit,
  isAccessoryType,
  isAnimation,
  isEmote,
  isLayeredClothing,
  isDynamicHead,
  isDynamicHeadInAssetList,
  isNonAvatarAssetType,
  isProfileBackground,
  buildMetaForAsset,
  insertAssetMetaIntoAssetList,
  buildMetaForAssets,
  maxNumberOfLayeredClothingItems,
  maxNumberOfAdvancedAccessoryItems,
  isBodyPart,
  layeredClothingRefinementOrderOffset,
  getCategories,
};
