import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Button, Icon, Link, SheetBody, SheetContent, SheetTitle } from "@rbx/foundation-ui";
import {
  Thumbnail2d,
  ThumbnailTypes,
  DefaultThumbnailSize,
  ThumbnailFormat,
} from "@rbx/thumbnails";
import { useTranslation } from "@rbx/core-scripts/react";
import { CurrentUser } from "@rbx/legacy-webapp-types/Roblox";
import { translateHtml } from "@rbx/translation-utils";

import serverListConstants from "../../../../js/serverList/constants/serverListConstants";
import serverListService from "../../../../js/serverList/services/serverListService";
import urlConstants from "../../../../js/serverList/constants/urlConstants";
import getEconomicRestrictionErrorMsg from "../../../../js/serverList/util/getEconomicRestrictionErrorMsg";
import usePrivateServerPurchase from "../../hooks/usePrivateServerPurchase";

import type { GameInstanceQueryParams } from "../../../../js/serverList/services/serverListService";

const { resources } = serverListConstants;

const TERMS_OF_USE_URL = "https://www.roblox.com/info/terms";

export type CreatePrivateServerSheetProps = {
  universeId: number;
  placeName: string;
  price: number;
  isPlusUser: boolean;
  isReady: boolean;
  canCreatePrivateServer: boolean;
  onClose: () => void;
  onServerCreated: (vipServerId: number) => void;
  refreshServers: (params?: GameInstanceQueryParams) => void;
  discounts?: { source: string; robux: number }[];
};

const CreatePrivateServerSheet = ({
  universeId,
  placeName,
  price,
  isPlusUser,
  isReady,
  canCreatePrivateServer,
  onClose,
  onServerCreated,
  refreshServers,
  discounts = [],
}: CreatePrivateServerSheetProps): React.ReactElement => {
  const { translate } = useTranslation();
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [displayPrivacyDisclaimer, setDisplayPrivacyDisclaimer] = useState(false);
  const [pspV2Enabled, setPspV2Enabled] = useState(false);
  const [privacyAcknowledged, setPrivacyAcknowledged] = useState(false);
  const discountTotal = discounts.reduce((sum, d) => sum + d.robux, 0);

  useEffect(() => {
    if (!CurrentUser.isUnder13) return;
    serverListService.getUserSettings().then(
      settings => {
        if (settings?.privateServerPrivacy === "NoOne") {
          setDisplayPrivacyDisclaimer(true);
        }
      },
      Function.prototype as () => void,
    );
  }, []);

  useEffect(() => {
    serverListService.getAccountSettingsGuacPolicy().then(
      policy => {
        if (policy?.isPrivateServerPrivacyV2Enabled) {
          setPspV2Enabled(true);
        }
      },
      Function.prototype as () => void,
    );
  }, []);

  const privacyDisclaimerRequired = displayPrivacyDisclaimer && pspV2Enabled;

  const autoGeneratedServerName = useMemo(
    () =>
      translate(resources.ownersServerText, {
        displayName: CurrentUser.displayName ?? CurrentUser.name,
      }),
    [translate],
  );

  const { createServer, isLoading } = usePrivateServerPurchase({
    universeId,
    price,
    refreshServers,
  });

  const handleCtaClick = useCallback(() => {
    setSubmitError(null);
    createServer({ serverName: autoGeneratedServerName })
      .then(data => {
        if (data.FailureReason !== undefined && data.ExpirationTimeInMinutes !== undefined) {
          setSubmitError(
            getEconomicRestrictionErrorMsg(
              translate,
              data.FailureReason,
              data.ExpirationTimeInMinutes,
            ),
          );
          return;
        }
        onServerCreated(data.vipServerId);
        onClose();
      })
      .catch((error: unknown) => {
        const errorData =
          error != null && typeof error === "object" && "data" in error
            ? // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
              (error as { data?: { errors?: { userFacingMessage?: string }[] } }).data
            : undefined;
        const errorMsg =
          errorData?.errors?.[0]?.userFacingMessage ?? translate(resources.purchaseError);
        setSubmitError(errorMsg);
      });
  }, [autoGeneratedServerName, createServer, onClose, onServerCreated, translate]);

  const ctaDisabled =
    !isReady ||
    !canCreatePrivateServer ||
    isLoading ||
    (privacyDisclaimerRequired && !privacyAcknowledged);

  return (
    <SheetContent
      centerSheetSize="Medium"
      closeLabel={translate("Action.Close")}
      largeScreenVariant="center"
    >
      <SheetTitle>
        {translate(
          isPlusUser
            ? resources.createPrivateServerSheetTitle
            : resources.subscribeToServerSheetTitle,
        )}
      </SheetTitle>
      <SheetBody>
        <div className="padding-x-xlarge padding-y-medium gap-y-xlarge flex flex-col">
          <div className="gap-medium flex flex-row items-center min-width-0">
            <div className="grow-0 shrink-0 basis-auto width-[72px] height-[72px]">
              <Thumbnail2d
                containerClass="radius-medium clip"
                format={ThumbnailFormat.jpeg}
                imgClassName="size-full"
                size={DefaultThumbnailSize}
                targetId={universeId}
                type={ThumbnailTypes.gameIcon}
              />
            </div>
            <div className="flex flex-col gap-y-xsmall min-width-0">
              <span className="text-title-medium content-emphasis text-truncate-end">
                {translate(resources.placeNamePrivateServer, { placeName })}
              </span>
              {isPlusUser ? (
                <span className="text-body-medium content-emphasis flex items-center gap-xsmall">
                  <span>
                    {discountTotal > 0
                      ? translate(resources.includedWithBlackbirdText)
                      : translate(resources.unlimitedIncludedWithBlackbirdText)}
                  </span>
                  {discountTotal > 0 && (
                    <span className="relative text-body-small content-muted flex items-center gap-xxsmall">
                      <Icon name="icon-filled-robux" size="XSmall" />
                      {translate(resources.pricePerMonthText, {
                        price: String(price + discountTotal),
                      })}
                      <span
                        style={{
                          position: "absolute",
                          left: 0,
                          right: 0,
                          top: "50%",
                          borderTop: "1px solid currentColor",
                        }}
                      />
                    </span>
                  )}
                </span>
              ) : (
                <span className="text-body-medium content-emphasis flex flex-row items-center gap-[2px]">
                  <Icon name="icon-filled-robux" size="Medium" />
                  <span>{translate(resources.pricePerMonthText, { price: String(price) })}</span>
                </span>
              )}
            </div>
          </div>

          {privacyDisclaimerRequired && (
            // eslint-disable-next-line jsx-a11y/label-has-associated-control
            <label className="flex items-start gap-x-small cursor-pointer">
              <input
                type="checkbox"
                checked={privacyAcknowledged}
                onChange={() => setPrivacyAcknowledged(prev => !prev)}
                className="grow-0 shrink-0 margin-top-[2px]"
              />
              <span className="text-caption-medium content-muted">
                {translateHtml(
                  (key: string) =>
                    translate(key, {
                      privacySettingsLink: `{linkStart}${translate(resources.privacySettingsText)}{linkEnd}`,
                    }),
                  resources.cantJoinPrivacySettingText,
                  [
                    {
                      opening: "linkStart",
                      closing: "linkEnd",
                      render: (children: React.ReactNode) => (
                        <Link
                          href={urlConstants.accountsSettingsPageUrl()}
                          target="_blank"
                          underline="always"
                          color="Standard"
                          isExternal={false}
                        >
                          {children}
                        </Link>
                      ),
                    },
                  ],
                )}
              </span>
            </label>
          )}

          <div className="flex flex-col gap-y-medium">
            <Button
              className="width-full"
              isDisabled={ctaDisabled}
              isLoading={isLoading}
              onClick={handleCtaClick}
              size="Medium"
              variant="Emphasis"
            >
              {translate(isPlusUser ? resources.createText : resources.subscribeText)}
            </Button>

            {submitError !== null && (
              <span className="text-caption-medium content-alert" role="alert">
                {submitError}
              </span>
            )}

            {!isPlusUser && (
              <span className="text-caption-medium content-muted">
                {translateHtml(translate, resources.subscriptionLegalText, [
                  {
                    opening: "linkStart",
                    closing: "linkEnd",
                    render: (children: React.ReactNode) => (
                      <Link
                        href={TERMS_OF_USE_URL}
                        target="_blank"
                        underline="always"
                        color="Standard"
                        isExternal={false}
                      >
                        {children}
                      </Link>
                    ),
                  },
                ])}
              </span>
            )}
          </div>
        </div>
      </SheetBody>
    </SheetContent>
  );
};

export default CreatePrivateServerSheet;
