import "@rbx/core-scripts/global";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Button, Icon, SheetRoot, Snackbar } from "@rbx/foundation-ui";
import {
  Thumbnail2d,
  ThumbnailFormat,
  ThumbnailGameIconSize,
  ThumbnailTypes,
  thumbnailService,
} from "@rbx/thumbnails";
import { useTranslation } from "@rbx/core-scripts/react";
import { CurrentUser, ItemPurchaseUpsellService } from "@rbx/legacy-webapp-types/Roblox";
import serverListConstants from "../../../../js/serverList/constants/serverListConstants";
import serverListService, {
  type GameInstanceQueryParams,
} from "../../../../js/serverList/services/serverListService";
import getEconomicRestrictionErrorMsg from "../../../../js/serverList/util/getEconomicRestrictionErrorMsg";
import { getJoinScript } from "../../../../js/serverList/util/gameInstanceUtil";
import usePrivateServerUpsellEvents from "../../hooks/usePrivateServerUpsellEvents";
import usePrivateServerPurchase from "../../hooks/usePrivateServerPurchase";

import CreatePrivateServerSheet from "./CreatePrivateServerSheet";

const { resources, serverListTypes } = serverListConstants;

type FirstServerCardProps = {
  universeId: number;
  title: React.ReactNode;
  subtitle: React.ReactNode;
  actions: React.ReactNode;
};

const FirstServerCard = ({ universeId, title, subtitle, actions }: FirstServerCardProps) => (
  <div className="flex flex-col gap-small padding-top-medium width-full large:flex-row large:wrap large:items-center">
    <div className="flex items-center gap-medium min-width-0 fill">
      <div className="grow-0 shrink-0 basis-auto width-[72px] height-[72px]">
        <Thumbnail2d
          type={ThumbnailTypes.gameIcon}
          targetId={universeId}
          containerClass="radius-medium clip"
          imgClassName="size-full"
        />
      </div>
      <div className="flex flex-col min-width-0">
        <span className="text-title-medium content-emphasis text-truncate-end">{title}</span>
        <span className="text-body-medium content-muted">{subtitle}</span>
      </div>
    </div>
    {actions}
  </div>
);

const CreateButton = ({
  label,
  onStart,
  isDisabled,
  variant = "Standard",
}: {
  label: string;
  onStart: () => void;
  isDisabled: boolean;
  variant?: "Standard" | "Emphasis";
}) => (
  <div className="grow-0 shrink-0 basis-auto width-full large:width-[200px]">
    <Button
      variant={variant}
      size="Medium"
      className="width-full"
      onClick={onStart}
      isDisabled={isDisabled}
    >
      {label}
    </Button>
  </div>
);

type CreateServerRowProps = {
  universeId: number;
  placeId: number;
  placeName: string;
  price: number;
  productId: number;
  sellerId: number;
  sellerName: string;
  isPlusUser: boolean;
  canCreatePrivateServer: boolean;
  refreshServers: (params?: GameInstanceQueryParams) => void;
  isReady: boolean;
  preopenCreatePrivateGame?: boolean;
  onOpenSheet?: () => void;
  hasExistingServers?: boolean;
  discounts?: { source: string; robux: number }[];
  disableRobloxPlusEntrypoints?: boolean;
};

const { ASSET_TYPE_ENUM } = window.RobloxItemPurchase;

const CreateServerRow = ({
  universeId,
  placeId,
  placeName,
  price,
  productId,
  sellerId,
  sellerName: _sellerName,
  isPlusUser,
  canCreatePrivateServer,
  refreshServers,
  isReady,
  preopenCreatePrivateGame = false,
  onOpenSheet,
  hasExistingServers = false,
  discounts = [],
  disableRobloxPlusEntrypoints = false,
}: CreateServerRowProps): React.ReactElement => {
  const { translate } = useTranslation();
  const { trackFreeWithPlusClick } = usePrivateServerUpsellEvents();

  const [createSheetOpen, setCreateSheetOpen] = useState(false);

  const autoGeneratedServerName = useMemo(
    () =>
      translate(resources.ownersServerText, {
        displayName: CurrentUser.displayName ?? CurrentUser.name,
      }),
    [translate],
  );

  const [directCreateError, setDirectCreateError] = useState<string | null>(null);

  const { createServer: createServerDirect, isLoading: isCreatingDirectly } =
    usePrivateServerPurchase({
      universeId,
      price,
      refreshServers,
      onError: errorMsg => {
        setDirectCreateError(errorMsg || translate(resources.purchaseError));
      },
    });

  const [pendingVipServerId, setPendingVipServerId] = useState<number | null>(null);
  const [createdServer, setCreatedServer] = useState<{
    vipServerId: number;
    accessCode: string;
    instanceId: string | null;
  } | null>(null);

  const handleDirectCreate = useCallback(() => {
    setDirectCreateError(null);
    createServerDirect({ serverName: autoGeneratedServerName })
      .then(data => {
        if (data.FailureReason !== undefined && data.ExpirationTimeInMinutes !== undefined) {
          setDirectCreateError(
            getEconomicRestrictionErrorMsg(
              translate,
              data.FailureReason,
              data.ExpirationTimeInMinutes,
            ),
          );
          return;
        }
        setPendingVipServerId(data.vipServerId);
      })
      .catch(Function.prototype as () => void);
  }, [autoGeneratedServerName, createServerDirect, translate]);

  const handleCreateSheetClose = useCallback(() => {
    setCreateSheetOpen(false);
  }, []);

  const handleServerCreated = useCallback((vipServerId: number) => {
    setPendingVipServerId(vipServerId);
  }, []);

  useEffect(() => {
    if (pendingVipServerId == null) return undefined;
    let cancelled = false;
    // The link-code path doesn't authorize the owner via their own link's allowlist.
    serverListService.getVipGameInstances(placeId, "").then(
      response => {
        if (cancelled) return;
        const fresh = response.data.data?.find(s => s.vipServerId === pendingVipServerId);
        if (fresh) {
          setCreatedServer({
            vipServerId: pendingVipServerId,
            accessCode: fresh.accessCode ?? "",
            instanceId: fresh.id ?? null,
          });
        }
        setPendingVipServerId(null);
      },
      () => {
        if (!cancelled) setPendingVipServerId(null);
      },
    );
    return () => {
      cancelled = true;
    };
  }, [pendingVipServerId, placeId]);

  // hasCloseAffordance=false per design — no onClose passed, so we clean up
  // state ourselves. Matches the Snackbar's internal auto-dismiss duration
  // for the action-present/short-title branch (7000ms) plus exit animation.
  useEffect(() => {
    if (createdServer == null) return undefined;
    const timeoutId = window.setTimeout(() => setCreatedServer(null), 7200);
    return () => window.clearTimeout(timeoutId);
  }, [createdServer]);

  useEffect(() => {
    if (preopenCreatePrivateGame) {
      setCreateSheetOpen(true);
    }
  }, [preopenCreatePrivateGame]);

  // Routes Robux shortfall through the legacy "exceed largest package" upsell
  // modal, which just sends the user to the Robux store. Auto-purchase
  // (`startItemUpsellProcess`) doesn't apply to private servers since we
  // always need a server-name input.
  const triggerInsufficientRobuxUpsell = useCallback(
    async (robux: number) => {
      let imageurl = "";
      try {
        const data = await thumbnailService.getThumbnailImage(
          ThumbnailTypes.gameIcon,
          ThumbnailGameIconSize.size150,
          ThumbnailFormat.webp,
          universeId,
        );
        const { thumbnail } = data as { thumbnail: { imageUrl?: string } };
        imageurl = thumbnail.imageUrl ?? "";
      } catch {
        // Fall through; redirect handled by the fallback callback.
      }
      ItemPurchaseUpsellService.showExceedLargestInsufficientRobuxModal(
        price - robux,
        {
          assetType: ASSET_TYPE_ENUM.PRIVATE_SERVER,
          expectedCurrency: "Robux",
          expectedPrice: String(price),
          expectedSellerId: String(sellerId),
          itemName: placeName,
          productId: String(productId),
          isPrivateServer: "true",
          isPlace: "false",
        },
        () => {
          window.location.href = "/upgrades/robux?ctx=upsell";
        },
        { userBalanceRobux: String(robux), imageurl, alerturl: "" },
        true,
      );
    },
    [price, placeName, productId, sellerId, universeId],
  );

  const openSheet = useCallback(() => {
    if (price > 0 && CurrentUser.userId) {
      serverListService.getCurrentUserBalance(Number(CurrentUser.userId)).then(
        ({ robux }) => {
          if (robux < price) {
            triggerInsufficientRobuxUpsell(robux).catch(() => {
              window.location.href = "/upgrades/robux?ctx=upsell";
            });
            return;
          }
          setCreateSheetOpen(true);
        },
        () => setCreateSheetOpen(true),
      );
      return;
    }
    setCreateSheetOpen(true);
  }, [price, triggerInsufficientRobuxUpsell]);

  const discountTotal = discounts.reduce((sum, d) => sum + d.robux, 0);
  const hasDiscount = discountTotal > 0;
  const originalPrice = price + discountTotal;
  const plusSubtitle = hasDiscount
    ? translate(resources.includedWithBlackbirdText)
    : translate(resources.unlimitedIncludedWithBlackbirdText);

  const isPaidNonPlus = !isPlusUser && price > 0;
  const isFreeNonPlus = !isPlusUser && price === 0;
  const buttonDisabled = !isReady || !canCreatePrivateServer;

  const createServerSheet = createSheetOpen ? (
    <SheetRoot
      data-testid="create-private-server-sheet-root"
      open
      onOpenChange={(nextOpen: boolean) => {
        if (!nextOpen) handleCreateSheetClose();
      }}
    >
      <CreatePrivateServerSheet
        canCreatePrivateServer={canCreatePrivateServer}
        discounts={discounts}
        isPlusUser={isPlusUser}
        isReady={isReady}
        onClose={handleCreateSheetClose}
        onServerCreated={handleServerCreated}
        placeName={placeName}
        price={price}
        refreshServers={refreshServers}
        universeId={universeId}
      />
    </SheetRoot>
  ) : null;

  const handleJoinCreatedServer = useCallback(() => {
    if (createdServer == null) return;
    const { accessCode, instanceId } = createdServer;
    getJoinScript(
      placeId,
      { instanceId, accessCode },
      serverListTypes.Vip.key,
      [],
      true,
      universeId,
    )();
  }, [createdServer, placeId, universeId]);

  const successSnackbar =
    createdServer !== null ? (
      <Snackbar
        title={translate(resources.privateServerCreatedText)}
        shouldAutoDismiss
        actions={
          <Button variant="Link" size="Medium" onClick={handleJoinCreatedServer}>
            {translate(resources.joinText)}
          </Button>
        }
      />
    ) : null;

  if (isPaidNonPlus && !hasExistingServers && !disableRobloxPlusEntrypoints) {
    return (
      <React.Fragment>
        <div className="flex flex-col gap-medium padding-top-medium width-full">
          <div className="flex items-center gap-medium min-width-0">
            <div className="grow-0 shrink-0 basis-auto width-[72px] height-[72px]">
              <Thumbnail2d
                type={ThumbnailTypes.gameIcon}
                targetId={universeId}
                containerClass="radius-medium clip"
                imgClassName="size-full"
              />
            </div>
            <div className="flex flex-col min-width-0">
              <span className="text-title-medium content-emphasis text-truncate-end">
                {translate(resources.placeNamePrivateServer, { placeName })}
              </span>
              <span className="text-body-medium content-muted">
                {translate(resources.requiresSubscriptionText)}
              </span>
            </div>
          </div>
          <div className="flex flex-col gap-small medium:flex-row">
            <div className="medium:fill">
              <Button
                variant="Emphasis"
                size="Medium"
                className="width-full"
                onClick={() => {
                  trackFreeWithPlusClick();
                  onOpenSheet?.();
                }}
              >
                {translate(resources.freeWithBlackbirdText)}
              </Button>
            </div>
            <div className="medium:fill">
              <Button
                variant="Standard"
                size="Medium"
                className="width-full"
                onClick={openSheet}
                isDisabled={buttonDisabled}
              >
                <span className="flex items-center justify-center gap-[2px]">
                  <Icon name="icon-filled-robux" size="Medium" />
                  <span>{translate(resources.pricePerMonthText, { price: String(price) })}</span>
                </span>
              </Button>
            </div>
          </div>
        </div>
        {createServerSheet}
        {successSnackbar}
      </React.Fragment>
    );
  }

  if (isFreeNonPlus && !hasExistingServers) {
    return (
      <React.Fragment>
        <FirstServerCard
          universeId={universeId}
          title={translate(resources.placeNamePrivateServer, { placeName })}
          subtitle={translate(resources.limitedToServersText)}
          actions={
            <React.Fragment>
              <CreateButton
                label={translate(resources.createOneForFreeText)}
                onStart={handleDirectCreate}
                isDisabled={buttonDisabled || isCreatingDirectly}
                variant="Emphasis"
              />
              {directCreateError !== null && (
                <span className="text-caption-medium content-alert">{directCreateError}</span>
              )}
            </React.Fragment>
          }
        />
        {successSnackbar}
      </React.Fragment>
    );
  }

  if (isPlusUser && !hasExistingServers) {
    return (
      <React.Fragment>
        <FirstServerCard
          universeId={universeId}
          title={translate(resources.placeNamePrivateServer, { placeName })}
          subtitle={
            hasDiscount ? (
              <span className="flex items-center gap-xsmall">
                <span>{translate(resources.includedWithBlackbirdText)}</span>
                <span className="relative text-body-small content-muted flex items-center gap-xxsmall">
                  <Icon name="icon-filled-robux" size="XSmall" />
                  {translate(resources.pricePerMonthText, {
                    price: String(originalPrice),
                  })}
                  <span
                    style={{
                      position: "absolute",
                      left: 0,
                      right: 0,
                      top: "50%",
                      borderTop: "1px solid currentColor",
                    }}
                  />
                </span>
              </span>
            ) : (
              plusSubtitle
            )
          }
          actions={
            <CreateButton
              label={translate(resources.createText)}
              onStart={openSheet}
              isDisabled={buttonDisabled}
              variant="Emphasis"
            />
          }
        />
        {createServerSheet}
        {successSnackbar}
      </React.Fragment>
    );
  }

  let subtitle: React.ReactNode;
  if (isPlusUser && hasDiscount) {
    subtitle = (
      <span className="flex items-center gap-xsmall">
        <span>{translate(resources.includedWithBlackbirdText)}</span>
        <span className="relative text-body-small content-muted flex items-center gap-xxsmall">
          <Icon name="icon-filled-robux" size="XSmall" />
          {translate(resources.pricePerMonthText, { price: String(originalPrice) })}
          <span
            style={{
              position: "absolute",
              left: 0,
              right: 0,
              top: "50%",
              borderTop: "1px solid currentColor",
            }}
          />
        </span>
      </span>
    );
  } else if (isPlusUser) {
    subtitle = plusSubtitle;
  } else if (price > 0) {
    subtitle = (
      <span className="flex items-center gap-[2px]">
        <Icon name="icon-filled-robux" size="Medium" />
        <span>{translate(resources.pricePerMonthText, { price: String(price) })}</span>
      </span>
    );
  } else if (!canCreatePrivateServer) {
    subtitle = translate(resources.freeServerLimitReachedText);
  } else {
    subtitle = translate(resources.limitedToServersText);
  }

  return (
    <React.Fragment>
      <div className="flex items-center justify-between padding-y-medium width-full">
        <div className="flex items-center gap-medium min-width-0">
          <div className="grow-0 shrink-0 basis-auto width-[40px] height-[40px] flex items-center justify-center radius-circle bg-shift-200">
            <Icon name="icon-filled-person-play" size="Medium" />
          </div>
          <div className="flex flex-col min-width-0">
            <span className="text-title-medium content-emphasis text-truncate-end">
              {translate(resources.createAPrivateServerText)}
            </span>
            <span className="text-body-medium content-muted">{subtitle}</span>
          </div>
        </div>

        <div className="grow-0 shrink-0 basis-auto [min-width:63px] large:width-[200px]">
          <Button
            variant="Standard"
            size="Small"
            className="width-full"
            onClick={isFreeNonPlus ? handleDirectCreate : openSheet}
            isDisabled={isFreeNonPlus ? buttonDisabled || isCreatingDirectly : buttonDisabled}
          >
            {translate(resources.createText)}
          </Button>
        </div>
      </div>
      {isFreeNonPlus && directCreateError !== null && (
        <span className="text-caption-medium content-alert">{directCreateError}</span>
      )}
      {!isFreeNonPlus && createServerSheet}
      {successSnackbar}
    </React.Fragment>
  );
};

export default CreateServerRow;
