export default {
  ageVerificationAMPFeature: "ShouldNotPromptIdVerificationUpsell",
  ageEstimationAMPFeature: "TriggerFacialAgeEstimationRecourse",
  allowParentLinkingAMPFeature: "ShouldPromptParentLinkUpsell",
  ageOfMajorityAmpFeature: "IsAboveAgeOfMajority",
  ageCorrectionAmpFeature: "CanCorrectAge",
  settingChangeAmpFeature: "CanChangeSetting",
  ShowUnderAgeFor17PlusSettingAmpFeature: "ShouldShowUnderAgeForSeventeenPlusSetting",
  ShowDisallowedCountryFor17PlusAmpFeature: "ShouldShowDisallowedCountryForSeventeenPlusSetting",
  IsCoppaApplicable: "IsCoppaApplicable",
  CanRemoveParentManagedUserBlocks: "CanRemoveParentManagedUserBlocks",
  CanRemoveParentManagedExperienceBlocks: "CanRemoveParentManagedExperienceBlocks",
  CanParentManageChildsFriends: "CanParentManageChildsFriends",
  CanParentManageChildsExperiences: "CanParentManageChildsExperiences",
  ShouldUserControlScreentimeLimit: "ShouldUserControlScreentimeLimit",
  DoesParentManageScreentime: "DoesParentManageScreentime",
  PlatformChatUserMessagesAllowed: "PlatformChatUserMessagesAllowed",
  Namespaces: {
    AccountManagement: "account_management/AccountManagement",
    AgeCorrection: "account_management/AgeCorrection",
    AgeCheck: "account_identity/AgeCheck",
    AgeCheckedPolicy: "account_management/AgeCheckedPolicy",
    UserSettingsPolicy: "account_management/UserSettingsPolicy",
    SettingsChange: "account_management/SettingsChange",
  },
};
