import { useQuery, type UseQueryOptions } from "@tanstack/react-query";
import * as httpService from "@rbx/core-scripts/http";
import serviceConstants from "../constants/serviceConstants";
import type {
  GetMyPrivateServersParams,
  GetMyPrivateServersResponse,
  MyPrivateServerResponse,
} from "../types/privateServerTypes";
import { parsePrivateServerWithDate } from "../utils/privateServerUtils";
import { privateServerKeys } from "./constants";

const getMyPrivateServers = async (
  cursor: string,
  itemsPerPage: number,
): Promise<GetMyPrivateServersResponse> => {
  const params: GetMyPrivateServersParams = {
    privateServersTab: "MyPrivateServers",
    cursor,
    itemsPerPage,
  };
  const { data } = await httpService.get<GetMyPrivateServersResponse>(
    serviceConstants.url.getMyPrivateServers(),
    params,
  );
  return data;
};

const getAllPrivateServers = async (): Promise<MyPrivateServerResponse[]> => {
  const SINGLE_PAGE_SIZE = 100;
  const MAX_CALLS = 100; // To prevent infinite looping; very generous limit of 10k private servers

  let cursor = "";
  let fullList: MyPrivateServerResponse[] = [];
  for (let i = 0; i < MAX_CALLS; i++) {
    // sequential calls to this endpoint is required. this is pre-existing behavior.
    // TODO: DMP-3754 or @jeffreyzhang to cleanup.
    // eslint-disable-next-line no-await-in-loop
    const result = await getMyPrivateServers(cursor, SINGLE_PAGE_SIZE);

    // Convert the ISO string expirationDate to a Date object for each server
    // Once we switch from manually calling the endpoint to autogenerated clients, we can remove this and have the client do it for us.
    fullList = [...fullList, ...result.data.map(parsePrivateServerWithDate)];
    if (!result.nextPageCursor) break;
    cursor = result.nextPageCursor;
  }

  return fullList;
};

type AllPrivateServersResponse = Awaited<ReturnType<typeof getAllPrivateServers>>;

type Options<TData = AllPrivateServersResponse> = Omit<
  UseQueryOptions<AllPrivateServersResponse, Error, TData>,
  "queryKey" | "queryFn"
>;

export function useGetAllPrivateServers(options: Options = {}) {
  return useQuery<AllPrivateServersResponse, Error>({
    queryKey: privateServerKeys.all(),
    queryFn: () => getAllPrivateServers(),
    // Do not retry - fetching all private servers can potentially be a lot of network requests
    retry: false,
    ...options,
  });
}
